### ISSUE TITLE
`clean_dataset.py` attempts and fails to load nonexistent, unnecessary `HKEmodel_dataset/test.json`

### ISSUE THREAD

**Issue by rcyeh** [TIAN-viola/DynRT#6]
```
% python clean_dataset.py 
Traceback (most recent call last):
  File "/github/DynRT/clean_dataset.py", line 25, in <module>
    test_json = json.load(open('HKEmodel_dataset/test.json', 'r', encoding='utf-8'))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'HKEmodel_dataset/test.json'
```

Where can I find the `HKEmodel_dataset/test.json`?

But is it needed? It seems that `clean_dataset.py` only checks that the lengths of the JSON objects match the sizes of the train, test, validation sets.

**Comment by rcyeh** [comment]
Hi folks, will you take pull requests?

**Comment by ji0929** [comment]
> ```
> % python clean_dataset.py 
> Traceback (most recent call last):
>   File "/github/DynRT/clean_dataset.py", line 25, in <module>
>     test_json = json.load(open('HKEmodel_dataset/test.json', 'r', encoding='utf-8'))
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'HKEmodel_dataset/test.json'
> ```
> 
> Where can I find the `HKEmodel_dataset/test.json`?
> 
> But is it needed? It seems that `clean_dataset.py` only checks that the lengths of the JSON objects match the sizes of the train, test, validation sets.

Hi, have you been able to solve the issue?😊

**Comment by rcyeh** [comment]
Just comment out the lines:

```
    test_json = json.load(open('HKEmodel_dataset/test.json', 'r', encoding='utf-8'))
    valid_json = json.load(open('HKEmodel_dataset/val.json', 'r', encoding='utf-8'))
    train_json = json.load(open('HKEmodel_dataset/train.json', 'r', encoding='utf-8'))
```

and also the occurrences of the same variables later.

**Comment by ji0929** [comment]
Thank you so much for your help!😊
